// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NBP;

#nullable disable

namespace NBP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230914125103_addDateToRate2")]
    partial class addDateToRate2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Models.NBPTable", b =>
                {
                    b.Property<Guid>("Id_Table")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Table");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("Models.Rate", b =>
                {
                    b.Property<Guid>("Id_Rate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Ask")
                        .HasColumnType("float");

                    b.Property<double>("Bid")
                        .HasColumnType("float");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id_Table")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Mid")
                        .HasColumnType("float");

                    b.HasKey("Id_Rate");

                    b.HasIndex("Id_Table");

                    b.ToTable("Rates");
                });

            modelBuilder.Entity("Models.Rate", b =>
                {
                    b.HasOne("Models.NBPTable", "Table")
                        .WithMany("Rates")
                        .HasForeignKey("Id_Table")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Models.NBPTable", b =>
                {
                    b.Navigation("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
